name: Notesocean CI

on:
  push:
    branches: [ "main" ]  

jobs:
  build:
    runs-on: self-hosted
  
    defaults:
      run:
        working-directory: /home/ubuntu/notesocean-node-front-end

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}        
    
    - name: "Checkout to Main branch"
      run: git checkout main

    - name: "Pull Latest code"
      run: git pull

    - name: "Install Dependencies"
      run: npm install

    - name: "Build for production"
      run: npm run start
